package dev.fleetrunner.buggarden

/**
 * Every word the app shows, in English, Spanish and German.
 *
 * Kept in Kotlin rather than in res/values-es and res/values-de because the
 * language is an in-app setting that changes the moment it is tapped, without
 * recreating the activity or touching the device locale. That also keeps the
 * device's language out of the experiment: an explorer on a German phone and
 * one on an English phone see the same app until one of them opens Settings.
 *
 * Plant names and Latin species are data, not copy, and are never translated.
 *
 * Two planted defects live here, both German-only and both switched off by
 * `garden_defects=false` (see [Garden.defects]):
 *   BG-12  the Settings title is the raw key "settings_title_v2".
 * The other German defect (BG-06, the blank invite screen) is in Screens.
 */
enum class Language(val code: String, val nativeName: String) {
    EN("en", "English"),
    ES("es", "Español"),
    DE("de", "Deutsch"),
}

enum class TextSize(val scale: Float) {
    SMALL(0.85f),
    DEFAULT(1.0f),
    LARGE(1.3f),
    LARGEST(1.6f),
}

data class Strings(
    // Sign in
    val appName: String = "Sprout",
    val signInTitle: String,
    val signInBody: String,
    val email: String,
    val password: String,
    val signIn: String,
    val continueAsGuest: String,
    val badCredentials: String,
    val signedOutNotice: String,
    val accountDeletedNotice: String,

    // Home
    val myPlants: String,
    val signedInAs: (String) -> String,
    val browsingAsGuest: String,
    val plantCount: (Int) -> String,
    val addPlant: String,
    val search: String,
    val settings: String,
    val profile: String,
    val recentlyViewed: (String) -> String,
    val tipOfTheDay: String,
    val tipBody: String,
    val emptyGarden: String,
    val inFavourites: String,

    // Summaries shared by the list and the detail screen
    val summary: (qty: Int, location: String, everyDays: Int) -> String,
    val watered: (daysAgo: Int) -> String,

    // Detail
    val back: String,
    val species: String,
    val location: String,
    val quantity: String,
    val waterEvery: String,
    val lastWatered: String,
    val notes: String,
    val days: (Int) -> String,
    val waterNow: String,
    val edit: String,
    val delete: String,
    val share: String,
    val addToFavourites: String,
    val removeFromFavourites: String,
    val deletePlantTitle: (String) -> String,
    val cannotBeUndone: String,
    val cancel: String,
    val deletedPlant: (String) -> String,

    // Add / edit
    val editPlant: String,
    val name: String,
    val speciesOptional: String,
    val locationOptional: String,
    val waterEveryDays: String,
    val notesOptional: String,
    val save: String,
    val saved: String,
    val nameRequired: String,
    val quantityRequired: String,
    val quantityWhole: String,
    val daysRange: String,

    // Search
    val searchPlants: String,
    val clearSearch: String,
    val results: (Int) -> String,
    val noMatches: (String) -> String,

    // Settings
    val settingsTitle: String,
    val appearance: String,
    val darkTheme: String,
    val darkThemeState: (Boolean) -> String,
    val language: String,
    val languageState: (String) -> String,
    val textSize: String,
    val textSizeName: (TextSize) -> String,
    val textSizeState: (String) -> String,
    val wateringReminders: String,
    val remindersState: (Boolean) -> String,
    val backUpNow: String,
    val backedUp: (Int) -> String,
    val aboutSprout: String,

    // Profile
    val freePlan: String,
    val onPlus: String,
    val upgrade: String,
    val plusTitle: String,
    val plusBody: String,
    val buy: String,
    val notNow: String,
    val inviteFriend: String,
    val signOut: String,
    val deleteAccount: String,
    val deleteAccountTitle: String,
    val deleteAccountBody: String,

    // Invite
    val inviteBody: String,
    val sharePlant: (String) -> String,
    val friendsEmail: String,
    val sendInvite: String,
    val inviteSent: (String) -> String,
    val invalidEmail: String,
    val copyLink: String,
    val linkCopied: String,

    // About
    val about: String,
    val version: (String) -> String,
    val ourStory: String,
    val aboutBody: String,
    val privacyLine: String,
)

private val english = Strings(
    signInTitle = "Sign in to your garden",
    signInBody = "Keep track of what you grow, where it lives and when it last had a drink.",
    email = "Email",
    password = "Password",
    signIn = "Sign in",
    continueAsGuest = "Continue as guest",
    badCredentials = "That email and password don't match.",
    signedOutNotice = "You have signed out.",
    accountDeletedNotice = "Your account has been deleted.",

    myPlants = "My plants",
    signedInAs = { "Signed in as $it" },
    browsingAsGuest = "Browsing as guest",
    plantCount = { if (it == 1) "1 plant" else "$it plants" },
    addPlant = "Add plant",
    search = "Search",
    settings = "Settings",
    profile = "Profile",
    recentlyViewed = { "Recently viewed: $it" },
    tipOfTheDay = "Tip of the day",
    tipBody = "Most houseplants would rather dry out a little than sit in wet soil.",
    emptyGarden = "No plants yet. Tap Add plant to start your garden.",
    inFavourites = "In your favourites",

    summary = { q, loc, d -> listOfNotNull("Qty $q", loc.ifBlank { null }, "every $d days").joinToString(" · ") },
    watered = { when (it) { 0 -> "Watered today"; 1 -> "Watered yesterday"; else -> "Watered $it days ago" } },

    back = "Back",
    species = "Species",
    location = "Location",
    quantity = "Quantity",
    waterEvery = "Water every",
    lastWatered = "Last watered",
    notes = "Notes",
    days = { if (it == 1) "1 day" else "$it days" },
    waterNow = "Water now",
    edit = "Edit",
    delete = "Delete",
    share = "Share",
    addToFavourites = "Add to favourites",
    removeFromFavourites = "Remove from favourites",
    deletePlantTitle = { "Delete $it?" },
    cannotBeUndone = "This can't be undone.",
    cancel = "Cancel",
    deletedPlant = { "Deleted $it" },

    editPlant = "Edit plant",
    name = "Name",
    speciesOptional = "Species (optional)",
    locationOptional = "Location (optional)",
    waterEveryDays = "Water every (days)",
    notesOptional = "Notes (optional)",
    save = "Save",
    saved = "Saved",
    nameRequired = "Name is required",
    quantityRequired = "Quantity is required",
    quantityWhole = "Quantity must be a whole number",
    daysRange = "Enter a number of days from 1 to 60",

    searchPlants = "Search plants",
    clearSearch = "Clear search",
    results = { if (it == 1) "1 result" else "$it results" },
    noMatches = { "No plants match \"$it\"" },

    settingsTitle = "Settings",
    appearance = "Appearance",
    darkTheme = "Dark theme",
    darkThemeState = { if (it) "Dark theme is on" else "Dark theme is off" },
    language = "Language",
    languageState = { "Language: $it" },
    textSize = "Text size",
    textSizeName = { when (it) { TextSize.SMALL -> "Small"; TextSize.DEFAULT -> "Default"; TextSize.LARGE -> "Large"; TextSize.LARGEST -> "Largest" } },
    textSizeState = { "Text size: $it" },
    wateringReminders = "Watering reminders",
    remindersState = { if (it) "Reminders are on" else "Reminders are off" },
    backUpNow = "Back up now",
    backedUp = { "Backed up $it plants to this phone" },
    aboutSprout = "About Sprout",

    freePlan = "Free plan",
    onPlus = "You're on Sprout Plus",
    upgrade = "Upgrade to Plus",
    plusTitle = "Sprout Plus",
    plusBody = "\$2.99 a month. Unlimited plants, photo notes and reminders.",
    buy = "Buy",
    notNow = "Not now",
    inviteFriend = "Invite a friend",
    signOut = "Sign out",
    deleteAccount = "Delete account",
    deleteAccountTitle = "Delete your account?",
    deleteAccountBody = "This removes your account and every plant in it.",

    inviteBody = "Send a friend an invite to Sprout. They'll get a link to start their own garden.",
    sharePlant = { "Share $it with a friend" },
    friendsEmail = "Friend's email",
    sendInvite = "Send invite",
    inviteSent = { "Invite sent to $it" },
    invalidEmail = "Enter a valid email address",
    copyLink = "Copy invite link",
    linkCopied = "Invite link copied",

    about = "About",
    version = { "Version $it" },
    ourStory = "Our story",
    aboutBody = "Sprout started as a notebook on a kitchen windowsill. It keeps track of your houseplants: what you have, where each one lives and when it last had a drink.",
    privacyLine = "Your garden stays on this phone. Nothing is uploaded.",
)

private val spanish = Strings(
    signInTitle = "Inicia sesión en tu jardín",
    signInBody = "Lleva la cuenta de lo que cultivas, dónde vive y cuándo lo regaste por última vez.",
    email = "Correo electrónico",
    password = "Contraseña",
    signIn = "Iniciar sesión",
    continueAsGuest = "Continuar como invitado",
    badCredentials = "El correo y la contraseña no coinciden.",
    signedOutNotice = "Has cerrado la sesión.",
    accountDeletedNotice = "Tu cuenta ha sido eliminada.",

    myPlants = "Mis plantas",
    signedInAs = { "Sesión iniciada como $it" },
    browsingAsGuest = "Navegando como invitado",
    plantCount = { if (it == 1) "1 planta" else "$it plantas" },
    addPlant = "Añadir planta",
    search = "Buscar",
    settings = "Ajustes",
    profile = "Perfil",
    recentlyViewed = { "Visto recientemente: $it" },
    tipOfTheDay = "Consejo del día",
    tipBody = "La mayoría de las plantas de interior prefieren secarse un poco antes que quedarse en tierra mojada.",
    emptyGarden = "Aún no hay plantas. Toca Añadir planta para empezar tu jardín.",
    inFavourites = "En tus favoritas",

    summary = { q, loc, d -> listOfNotNull("Cant. $q", loc.ifBlank { null }, "cada $d días").joinToString(" · ") },
    watered = { when (it) { 0 -> "Regada hoy"; 1 -> "Regada ayer"; else -> "Regada hace $it días" } },

    back = "Atrás",
    species = "Especie científica",
    location = "Ubicación en casa",
    quantity = "Cantidad de ejemplares",
    waterEvery = "Frecuencia de riego",
    lastWatered = "Último riego registrado",
    notes = "Notas",
    days = { if (it == 1) "1 día" else "$it días" },
    waterNow = "Regar ahora",
    edit = "Editar",
    delete = "Eliminar",
    share = "Compartir",
    addToFavourites = "Añadir a favoritas",
    removeFromFavourites = "Quitar de favoritas",
    deletePlantTitle = { "¿Eliminar $it?" },
    cannotBeUndone = "Esto no se puede deshacer.",
    cancel = "Cancelar",
    deletedPlant = { "$it eliminada" },

    editPlant = "Editar planta",
    name = "Nombre",
    speciesOptional = "Especie (opcional)",
    locationOptional = "Ubicación (opcional)",
    waterEveryDays = "Regar cada (días)",
    notesOptional = "Notas (opcional)",
    save = "Guardar",
    saved = "Guardado",
    nameRequired = "El nombre es obligatorio",
    quantityRequired = "La cantidad es obligatoria",
    quantityWhole = "La cantidad debe ser un número entero",
    daysRange = "Introduce un número de días entre 1 y 60",

    searchPlants = "Buscar plantas",
    clearSearch = "Borrar búsqueda",
    results = { if (it == 1) "1 resultado" else "$it resultados" },
    noMatches = { "Ninguna planta coincide con \"$it\"" },

    settingsTitle = "Ajustes",
    appearance = "Apariencia",
    darkTheme = "Tema oscuro",
    darkThemeState = { if (it) "El tema oscuro está activado" else "El tema oscuro está desactivado" },
    language = "Idioma",
    languageState = { "Idioma: $it" },
    textSize = "Tamaño del texto",
    textSizeName = { when (it) { TextSize.SMALL -> "Pequeño"; TextSize.DEFAULT -> "Normal"; TextSize.LARGE -> "Grande"; TextSize.LARGEST -> "Muy grande" } },
    textSizeState = { "Tamaño del texto: $it" },
    wateringReminders = "Recordatorios de riego",
    remindersState = { if (it) "Recordatorios activados" else "Recordatorios desactivados" },
    backUpNow = "Copia de seguridad",
    backedUp = { "$it plantas guardadas en este teléfono" },
    aboutSprout = "Acerca de Sprout",

    freePlan = "Plan gratuito",
    onPlus = "Tienes Sprout Plus",
    upgrade = "Pasar a Plus",
    plusTitle = "Sprout Plus",
    plusBody = "2,99 \$ al mes. Plantas, notas con fotos y recordatorios ilimitados.",
    buy = "Comprar",
    notNow = "Ahora no",
    inviteFriend = "Invitar a un amigo",
    signOut = "Cerrar sesión",
    deleteAccount = "Eliminar cuenta",
    deleteAccountTitle = "¿Eliminar tu cuenta?",
    deleteAccountBody = "Se eliminarán tu cuenta y todas tus plantas.",

    inviteBody = "Envía a un amigo una invitación a Sprout. Recibirá un enlace para empezar su propio jardín.",
    sharePlant = { "Compartir $it con un amigo" },
    friendsEmail = "Correo de tu amigo",
    sendInvite = "Enviar invitación",
    inviteSent = { "Invitación enviada a $it" },
    invalidEmail = "Introduce un correo válido",
    copyLink = "Copiar enlace",
    linkCopied = "Enlace copiado",

    about = "Acerca de",
    version = { "Versión $it" },
    ourStory = "Nuestra historia",
    aboutBody = "Sprout empezó como un cuaderno en la ventana de una cocina. Lleva la cuenta de tus plantas: cuáles tienes, dónde vive cada una y cuándo la regaste por última vez.",
    privacyLine = "Tu jardín se queda en este teléfono. No se sube nada.",
)

private val german = Strings(
    signInTitle = "Melde dich bei deinem Garten an",
    signInBody = "Behalte im Blick, was du anbaust, wo es steht und wann es zuletzt Wasser bekam.",
    email = "E-Mail",
    password = "Passwort",
    signIn = "Anmelden",
    continueAsGuest = "Als Gast fortfahren",
    badCredentials = "E-Mail und Passwort passen nicht zusammen.",
    signedOutNotice = "Du hast dich abgemeldet.",
    accountDeletedNotice = "Dein Konto wurde gelöscht.",

    myPlants = "Meine Pflanzen",
    signedInAs = { "Angemeldet als $it" },
    browsingAsGuest = "Als Gast unterwegs",
    plantCount = { if (it == 1) "1 Pflanze" else "$it Pflanzen" },
    addPlant = "Pflanze hinzufügen",
    search = "Suchen",
    settings = "Einstellungen",
    profile = "Profil",
    recentlyViewed = { "Zuletzt angesehen: $it" },
    tipOfTheDay = "Tipp des Tages",
    tipBody = "Die meisten Zimmerpflanzen trocknen lieber etwas ab, als in nasser Erde zu stehen.",
    emptyGarden = "Noch keine Pflanzen. Tippe auf Pflanze hinzufügen, um zu beginnen.",
    inFavourites = "In deinen Favoriten",

    summary = { q, loc, d -> listOfNotNull("Anz. $q", loc.ifBlank { null }, "alle $d Tage").joinToString(" · ") },
    watered = { when (it) { 0 -> "Heute gegossen"; 1 -> "Gestern gegossen"; else -> "Vor $it Tagen gegossen" } },

    back = "Zurück",
    species = "Art",
    location = "Standort",
    quantity = "Anzahl",
    waterEvery = "Gießen alle",
    lastWatered = "Zuletzt gegossen",
    notes = "Notizen",
    days = { if (it == 1) "1 Tag" else "$it Tage" },
    waterNow = "Jetzt gießen",
    edit = "Bearbeiten",
    delete = "Löschen",
    share = "Teilen",
    addToFavourites = "Zu Favoriten hinzufügen",
    removeFromFavourites = "Aus Favoriten entfernen",
    deletePlantTitle = { "$it löschen?" },
    cannotBeUndone = "Das lässt sich nicht rückgängig machen.",
    cancel = "Abbrechen",
    deletedPlant = { "$it gelöscht" },

    editPlant = "Pflanze bearbeiten",
    name = "Name",
    speciesOptional = "Art (optional)",
    locationOptional = "Standort (optional)",
    waterEveryDays = "Gießen alle (Tage)",
    notesOptional = "Notizen (optional)",
    save = "Speichern",
    saved = "Gespeichert",
    nameRequired = "Name ist erforderlich",
    quantityRequired = "Anzahl ist erforderlich",
    quantityWhole = "Die Anzahl muss eine ganze Zahl sein",
    daysRange = "Gib eine Zahl von 1 bis 60 Tagen ein",

    searchPlants = "Pflanzen suchen",
    clearSearch = "Suche löschen",
    results = { if (it == 1) "1 Ergebnis" else "$it Ergebnisse" },
    noMatches = { "Keine Pflanze passt zu \"$it\"" },

    // PLANTED BG-12 lives in Garden.strings(): with defects on, this title is
    // replaced by the raw key "settings_title_v2".
    settingsTitle = "Einstellungen",
    appearance = "Darstellung",
    darkTheme = "Dunkles Design",
    darkThemeState = { if (it) "Dunkles Design ist an" else "Dunkles Design ist aus" },
    language = "Sprache",
    languageState = { "Sprache: $it" },
    textSize = "Textgröße",
    textSizeName = { when (it) { TextSize.SMALL -> "Klein"; TextSize.DEFAULT -> "Standard"; TextSize.LARGE -> "Groß"; TextSize.LARGEST -> "Sehr groß" } },
    textSizeState = { "Textgröße: $it" },
    wateringReminders = "Gießerinnerungen",
    remindersState = { if (it) "Erinnerungen sind an" else "Erinnerungen sind aus" },
    backUpNow = "Jetzt sichern",
    backedUp = { "$it Pflanzen auf diesem Telefon gesichert" },
    aboutSprout = "Über Sprout",

    freePlan = "Kostenloser Tarif",
    onPlus = "Du hast Sprout Plus",
    upgrade = "Plus holen",
    plusTitle = "Sprout Plus",
    plusBody = "2,99 \$ im Monat. Unbegrenzt Pflanzen, Fotonotizen und Erinnerungen.",
    buy = "Kaufen",
    notNow = "Nicht jetzt",
    inviteFriend = "Freund einladen",
    signOut = "Abmelden",
    deleteAccount = "Konto löschen",
    deleteAccountTitle = "Konto löschen?",
    deleteAccountBody = "Dein Konto und alle deine Pflanzen werden entfernt.",

    inviteBody = "Lade einen Freund zu Sprout ein. Er bekommt einen Link, um seinen eigenen Garten anzulegen.",
    sharePlant = { "$it mit einem Freund teilen" },
    friendsEmail = "E-Mail deines Freundes",
    sendInvite = "Einladung senden",
    inviteSent = { "Einladung an $it gesendet" },
    invalidEmail = "Gib eine gültige E-Mail-Adresse ein",
    copyLink = "Link kopieren",
    linkCopied = "Link kopiert",

    about = "Über",
    version = { "Version $it" },
    ourStory = "Unsere Geschichte",
    aboutBody = "Sprout begann als Notizbuch auf einer Küchenfensterbank. Es merkt sich deine Zimmerpflanzen: welche du hast, wo jede steht und wann sie zuletzt Wasser bekam.",
    privacyLine = "Dein Garten bleibt auf diesem Telefon. Nichts wird hochgeladen.",
)

fun stringsFor(language: Language): Strings = when (language) {
    Language.EN -> english
    Language.ES -> spanish
    Language.DE -> german
}
